server:
  port: 8180

spring:
  cloud:
    gateway:
      routes:
        - id: hello_world
          uri: http://localhost:8280
          predicates:
            - Path=/api/hello
          filters:
            - SetPath=/hello
  data:
    mongodb:
      database: sessiondb